# Generated by Django 4.2 on 2023-05-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=models.TextField(max_length=2000),
        ),
    ]
